PES-128: install and uninstall refactor
Zasilkovna/prestashop pull request #104
Opened 2021-06-11 12:23 UTC by jan-potuznik-z

2021-08-13 08:20 UTC, FJiskra requested changes

2021-08-13 08:20 UTC, FJiskra commented on packetery/libs/Module/Uninstaller.php
> +        $sql[] = 'RENAME TABLE `' . _DB_PREFIX_ . 'packetery_order` TO `' . _DB_PREFIX_ . 'packetery_order_backup`';
Pokud se u backup table nebudou řešit migrace, tak by někde měla být verze schématu, aby na to případný script mohl reagovat.

2021-08-13 08:20 UTC, FJiskra commented on packetery/translations/cs.php
> +$_MODULE['<{packetery}prestashop>packetery_9aa49c5a01dab7e49c73343b47e995a2'] = 'Vyberte prosím výdejní místo';
Jak toto souvisí s úkolem?

2021-08-16 13:48 UTC, jan-potuznik-z commented on packetery/libs/Module/Uninstaller.php
> +        $sql[] = 'RENAME TABLE `' . _DB_PREFIX_ . 'packetery_order` TO `' . _DB_PREFIX_ . 'packetery_order_backup`';
Je to jen záchranná brzda, migrace řešeny nebudou. Co myslíš případným skriptem?

2021-08-16 13:50 UTC, jan-potuznik-z commented on packetery/translations/cs.php
> +$_MODULE['<{packetery}prestashop>packetery_9aa49c5a01dab7e49c73343b47e995a2'] = 'Vyberte prosím výdejní místo';
Oprava, která se tam dostala při rebase. Odstraňuji, udělám samostatný PR.

2021-08-16 13:51 UTC, jan-potuznik-z commented on packetery/libs/Module/Installer.php
> +            define('_MYSQL_ENGINE_', 'MyISAM');
Převzatý kód, reálně to nenastává, protože je definováno jako InnoDB. Měním na InnoDB a raději nechávám.

2021-08-16 13:56 UTC, jan-potuznik-z commented on packetery/libs/Module/Uninstaller.php
> +            'UPDATE `' . _DB_PREFIX_ . 'carrier` SET `is_module` = 0, `external_module_name` = NULL, `need_range` = 0
Šlo by využít Db->update() , ale takto je to kratší a přehledné. Carrier na to metodu nemá.

2021-08-17 06:57 UTC, FJiskra commented on packetery/libs/Module/Uninstaller.php
> +            'UPDATE `' . _DB_PREFIX_ . 'carrier` SET `is_module` = 0, `external_module_name` = NULL, `need_range` = 0
Já myslel něco jako CarrierService::disableModule()

2021-08-17 07:14 UTC, FJiskra commented on packetery/libs/Module/Uninstaller.php
> +        $sql[] = 'RENAME TABLE `' . _DB_PREFIX_ . 'packetery_order` TO `' . _DB_PREFIX_ . 'packetery_order_backup`';
Mám na mysli kód, který provede export z backup tabulky.

2021-08-17 09:22 UTC, FJiskra commented on packetery/libs/Module/Installer.php
> +            define('_MYSQL_ENGINE_', 'MyISAM');
Použít natvrdo InnoDB

2021-08-17 09:26 UTC, FJiskra commented on packetery/libs/Module/Installer.php
> +            define('_MYSQL_ENGINE_', 'MyISAM');
ten ENGINE u sql by se neměl brát z konstanty, ale mělo by to být v metodě na tvrdo

2021-08-17 14:28 UTC, merged