Pes 279 editable weight
Zasilkovna/prestashop pull request #126
Opened 2021-08-24 10:19 UTC by jan-potuznik-z

2021-08-24 10:57 UTC, FJiskra commented on packetery/packetery.class.php
> +     * @param $orders
vždy array?

2021-08-24 11:24 UTC, FJiskra commented on packetery/libs/Order/Ajax.php
> +    public function setWeights()
připodobnil bych to ke controlleru. Takže actionSetWeights nebo handleSetWeights. nelíbí se mi to že metoda setX vrací něco jiného než void/$this.

2021-08-24 11:25 UTC, FJiskra commented on packetery/libs/Order/Ajax.php
> +            return 'No order weights to set provided.';
Pokud to vidí uživatel, tak přeložit

2021-08-24 12:10 UTC, jan-potuznik-z commented on packetery/libs/Order/Ajax.php
> +            return 'No order weights to set provided.';
Nevidí.

2021-08-24 12:19 UTC, jan-potuznik-z commented on packetery/packetery.class.php
> +     * @param $orders
Upraveno.

2021-08-25 14:35 UTC, packeta requested changes

2021-08-25 14:35 UTC, packeta commented on packetery/libs/Order/OrderRepository.php
> +    public function getWeights($orderIds)
getWeights(array $orderIds)

2021-08-25 14:35 UTC, packeta commented on packetery/packetery.class.php
> +    public static function loadWeightToOrders($orders)
loadWeightToOrders(array $orders)

2021-08-28 16:51 UTC, merged