Pes 763 adult verification product detail checkbox
Zasilkovna/prestashop pull request #211
Opened 2022-04-25 09:56 UTC by JaroslavNaleznyPacketa

2022-04-26 06:40 UTC, packeta requested changes

2022-04-26 06:40 UTC, packeta commented on packetery/packetery.php
> +            $this->context->smarty->assign('adminToken', $adminToken);
Co kdybychom šabloně předávali celý link: `$this->context->link->getAdminLink('AdminProducts')` ? Pokud by jsi vytvářel v šabloně více odkazů, můžeš si předat celý `$this->context->link`

2022-04-26 06:40 UTC, packeta commented on packetery/packetery.php
> +            $sql = 'SELECT `is_adult` FROM `' . _DB_PREFIX_ . 'packetery_product` WHERE `id_product` = ' . (int)$idProduct;
idProduct je už int.  Na int to převádíš, když parametr získáváš z params.

2022-04-26 06:40 UTC, packeta commented on packetery/packetery.php
> +                'id_product' => $idProduct,
Co když se ti vrátí neexistující ID produktu ? Neměl by jsi nejdřív ověřit, že produkt s tímto ID opravdu existuje ?

2022-04-26 13:05 UTC, JaroslavNaleznyPacketa commented on packetery/libs/Module/Installer.php
> +        $sql[] = 'CREATE TABLE `' . _DB_PREFIX_ . 'packetery_product` (
Opraveno, Tabulka se nyní vytváří i v upgrade-3.0.0.php a odstraňuje v Uninstaller.php

2022-04-26 13:07 UTC, JaroslavNaleznyPacketa commented on packetery/packetery.php
> +            'actionProductUpdate',
Chybějící hook přídán.

2022-04-27 10:27 UTC, JaroslavNaleznyPacketa commented on packetery/packetery.php
> +        $idProduct = (int)\Packetery\Tools\Tools::getValue('id_product');
Ano, i tam se dá získat.

2022-04-27 10:31 UTC, JaroslavNaleznyPacketa commented on packetery/packetery.php
> +            $sql = 'SELECT `is_adult` FROM `' . _DB_PREFIX_ . 'packetery_product` WHERE `id_product` = ' . (int)$idProduct;
Jako id použiji id objektu prestashop produktu, kde je typ specifikovaný

2022-04-27 10:38 UTC, JaroslavNaleznyPacketa commented on packetery/packetery.php
> +                'is_adult' => $packeteryAgeVerification,
packetery_age_verification musí být volaný v proměnné, jelikož přestashop nechecknutý checbox neodesílá, proto getIsset. Musí být navíc natypovaný na int (int)Tools::getIsset('packetery_age_verification') abych dostal true /false.

2022-04-27 12:10 UTC, JaroslavNaleznyPacketa commented on packetery/packetery.php
> +            if (\Packetery\Tools\Tools::version_compare(_PS_VERSION_, '1.7.0', '<')) $version = '1.6';
pro přehlednost přejmenovávám na packetery_product_attribute

2022-04-28 09:19 UTC, packeta requested changes

2022-04-28 09:19 UTC, packeta commented on packetery/libs/Order/OrderExporter.php
> +
zbytečná řádka, prosím o odstranění

2022-04-28 09:19 UTC, packeta commented on packetery/libs/Order/OrderExporter.php
> +            'adultContent' => $adultContent,
Pokud `$orderRepository->isOrderAdult($order->id);` používáš na jednom místě, je zbytečné to extrahovat do zvláštní proměnné. `$orderRepository->isOrderAdult($order->id);` můžeš zavolat přímo zde.

2022-04-28 09:19 UTC, packeta commented on packetery/libs/Order/OrderRepository.php
> +        return (bool) $this->dbTools->getValue($sql);
Před return dej prosím mezeru

2022-04-28 09:19 UTC, packeta commented on packetery/packetery.php
> +     * @throws Packetery\Exceptions\DatabaseException
Tyto změny se nějak týkají tohoto ticketu?

2022-04-28 09:19 UTC, packeta commented on packetery/packetery.php
> +            $idProduct = (int)\Packetery\Tools\Tools::getValue('id_product');
Opravdu je potřeba ID produktu zjišťovat v každé verzi PS jinak ?

2022-04-28 09:19 UTC, packeta commented on packetery/packetery.php
> +        $productAttributeInfo = $productAttribute->getValue($params['product']->id, 'id_product');
$params['product'] používáš na několika místech. V tomto případě bych si jej vytáhnul do vlastní proměnné např. $product.  Pak můžeš volat $product->id ...

2022-04-28 10:30 UTC, JaroslavNaleznyPacketa commented on packetery/packetery.php
> +     * @throws Packetery\Exceptions\DatabaseException
nesouvisí, u všech vracím zpět

2022-04-28 10:39 UTC, JaroslavNaleznyPacketa commented on packetery/packetery.php
> +            $idProduct = (int)\Packetery\Tools\Tools::getValue('id_product');
Není potřeba, vracím zpět.

2022-04-29 06:43 UTC, packeta requested changes

2022-04-29 06:43 UTC, packeta commented on packetery/packetery.php
> +     * @throws Packetery\Exceptions\DatabaseException
Tato změna nesouvisí s ticketem.

2022-04-29 06:43 UTC, packeta commented on packetery/views/js/back.js
> +        var actualPrudoctType = $('[name="type_product"]:checked').val();
Proč zrovna název `actualPrudoctType ` ?

2022-04-29 06:43 UTC, packeta commented on packetery/views/js/back.js
> +    if (actualPrudoctType == 0) {
Doporučuji podmínku obrátit `if  (actualPrudoctType  === 2) {$('#link-ModulePacketery').hide() ...`

2022-04-29 10:30 UTC, JaroslavNaleznyPacketa commented on packetery/views/js/back.js
> +        var actualPrudoctType = $('[name="type_product"]:checked').val();
typo, opraveno

2022-04-29 10:30 UTC, JaroslavNaleznyPacketa commented on packetery/packetery.php
> +     * @throws Packetery\Exceptions\DatabaseException
opraveno

2022-04-29 15:02 UTC, JaroslavNaleznyPacketa commented on packetery/packetery.php
> +        if ($productAttributeInfo['id_product']) {
opraveno

2022-04-29 15:09 UTC, JaroslavNaleznyPacketa commented on packetery/views/js/back.js
> +    if (actualProductType === 2) {
vysvětlivky přidány

2022-04-29 16:12 UTC, merged