PES-1173_split_pickup_points
Zasilkovna/prestashop pull request #240
Opened 2023-02-06 17:02 UTC by MMozola

2023-02-08 11:38 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierAdminForm.php
> +    public function saveCarrierOptions($carrierData, $apiCarrier) {
chybí phpdoc

2023-02-08 11:38 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierAdminForm.php
> +    private function getPossibleVendors()
chybí phpdoc

2023-02-08 11:38 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierAdminForm.php
> +     * @param array|null $possibleVendors
aktualizovat phpdoc

2023-02-08 11:38 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierAdminForm.php
> +        if ($apiCarrier['id'] === Packetery::PP_ALL || $apiCarrier['id'] === Packetery::ZPOINT ) {
code style

2023-02-08 11:38 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierAdminForm.php
> +            if (isset($formData[$vendorFormName]) && (bool) $formData[$vendorFormName] === true) {
code style

2023-02-08 11:38 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierVendors.php
> +            $countriesVendor = $vendorData['countries'];
spíš vendorCountries

2023-02-08 11:38 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierAdminForm.php
> +        }else if (!empty($possibleVendors)) {
code style

2023-02-08 11:38 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierTools.php
> +    public static function getEditLink($carrierId)
Testoval jsi v nižší verzích? Není tady potřeba podobná podmínka jako v Packetery::getAdminLink ?

2023-02-08 11:38 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierAdminForm.php
> +        $pickupPointType = $apiCarrier['is_pickup_points'] ? ($branchId === Packetery::ZPOINT ? 'internal' : 'external') : null;
Tenhle zanořený ternár už tam máš 2x - metoda?

2023-02-08 11:38 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierAdminForm.php
> +        $allowedVendors = ($carrierData['id_branch'] === Packetery::ZPOINT || $carrierData['id_branch'] === Packetery::PP_ALL) ? $this->getAllowedVendorsJsonFromForm($formData) : json_encode([$carrie
Chtělo by to přehlednější zápis.

2023-02-08 11:38 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierAdminForm.php
> +        if($branchId !== Packetery::ZPOINT && $branchId !== Packetery::PP_ALL) {
code style

2023-02-08 11:50 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierAdminForm.php
> +        $helper = new HelperForm();
vytvoření instance bych přesunul až před její použití

2023-02-08 11:59 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierAdminForm.php
> +            $countries = [$apiCarrier['country']];
Undefined index: country

2023-02-08 11:59 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierAdminForm.php
> +        if ((bool) $apiCarrier['disallows_cod'] === false) {
Undefined index: disallows_cod

2023-02-08 12:04 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierAdminForm.php
> -        $helper->show_cancel_button = true;
show_cancel_button dej k oběma formulářům, poskytuje to navigační prvek pro návrat na seznam dopravců

2023-02-09 13:17 UTC, jan-potuznik-z commented on packetery/libs/Carrier/CarrierAdminForm.php
> +    private function getBackButton()
Jakou výhodu to má oproti show_cancel_button? Jako nevýhody beru vlastní skládání adresy a výčet tříd.

2023-02-09 13:17 UTC, jan-potuznik-z commented on packetery/views/js/back.js
> +$(document).on('change', '[name="type_product"]', function() {
Proč funkční kód, který nesouvisí s ticketem, nahrazuješ nefunkčním?

2023-02-13 09:42 UTC, MMozola commented on packetery/libs/Carrier/CarrierAdminForm.php
> +    private function getBackButton()
Cancel button dělá tohle:
This defaults to false. If set to true, a cancel button is displayed at the bottom of the form. Clicking on it returns to the previous page in the browser’s history.

Což nefunguje když vícekrát uložím formulář. Když tam je ten odkaz napřímo, tak mě to vždycky dostane na výpis dopravců.

2023-03-17 07:59 UTC, packeta requested changes

2023-03-17 07:59 UTC, packeta commented on packetery/controllers/admin/PacketeryCarrierGridController.php
> +        return '<a class="edit btn btn-default" href="' . CarrierTools::getEditLink($carrierId) . '"><i class="icon-pencil"></i> ' . $this->l('Edit', 'packeterycarriergridcontroller') . '</a>';
html odkazy dáváme běžně do tpl šablon (viz.  trackingLink.tpl, link.tpl, packeteryTrackingLink.tpl.  Proč to neděláme i v tomto případě a html kód máme v controlleru ? O vykreslení html kódu by se měla starat šablonovací vrstva, ne controller.

2023-03-17 07:59 UTC, packeta commented on packetery/libs/Carrier/CarrierTools.php
> +        return array_pop($zonesAndCountries);
před return chybí prázdný řádek

2023-03-17 07:59 UTC, packeta commented on packetery/libs/Carrier/CarrierTools.php
> +        return array_pop($zonesAndCountries);
metoda která může vrátit více typů (mixed) zavání špatným návrhem.  Zkus se nad tím prosím zamyslet a vymyslet lepší variantu.

2023-03-17 07:59 UTC, packeta commented on packetery/libs/Carrier/CarrierVendors.php
> +    public function getVendors()
u metody chybí komentář

2023-03-17 07:59 UTC, packeta commented on packetery/packetery.php
> +        }else{
špatně použitý coding style mezi chlupatými závorkami a "else" má být mezera

2023-03-17 07:59 UTC, packeta commented on packetery/libs/Carrier/CarrierVendors.php
> +
Prázdný řádek navíc.

2023-03-17 07:59 UTC, packeta commented on packetery/libs/Carrier/CarrierRepository.php
> +            $carrierUpdate = ['is_module' => 0, 'external_module_name' => null, 'need_range' => 0, 'allowed_vendors' => null];
poslední prvek v poli končí čárkou.  Chybějící čárku na konci poli doplň i na ostatních místech. Zde bych také pole už naformátoval

2023-03-17 07:59 UTC, packeta commented on packetery/libs/Carrier/CarrierTools.php
> +    public function getCountries($carrierId, $countryParam = 'name') {
chybný coding style ,  chlupatou závorku píšeme u metody na nový řádek.

2023-03-21 07:25 UTC, packeta requested changes

2023-03-21 07:32 UTC, packeta requested changes

2023-03-21 07:32 UTC, packeta commented on packetery/controllers/admin/PacketeryCarrierGridController.php
> +        return $smarty->fetch(dirname(__FILE__) . '/../../views/templates/admin/link.tpl');
Co mají řádky 186-191 společného se splitem ?

2023-03-21 07:51 UTC, jan-potuznik-z commented on packetery/controllers/admin/PacketeryCarrierGridController.php
> +        return $smarty->fetch(dirname(__FILE__) . '/../../views/templates/admin/link.tpl');
Viz https://github.com/Zasilkovna/prestashop/pull/240#discussion_r1139869099

2023-03-21 08:31 UTC, merged