PES-1266: orders grid refactor
Zasilkovna/prestashop pull request #244
Opened 2023-03-01 16:16 UTC by MMozola

2023-03-03 11:56 UTC, jan-potuznik-z commented on packetery/controllers/admin/PacketeryOrderGridController.php
> -        $this->addRowAction('edit');
Přestaly fungovat hromadné akce. Myslím, že to souvisí.

2023-03-03 11:56 UTC, jan-potuznik-z commented on packetery/controllers/admin/PacketeryOrderGridController.php
> +        if(empty($row['id_order'])) {
code style

2023-03-03 11:56 UTC, jan-potuznik-z commented on packetery/controllers/admin/PacketeryOrderGridController.php
> +        if(empty($customerFullName)) {
code style

2023-03-03 11:56 UTC, jan-potuznik-z commented on packetery/controllers/admin/PacketeryOrderGridController.php
> +            } elseif($nameArrayIndex === $nameMaxIndex) {
code style

2023-03-03 11:56 UTC, jan-potuznik-z commented on packetery/controllers/admin/PacketeryOrderGridController.php
> +            if ($nameArrayIndex < $nameMaxIndex) {
Předělej to prosím na jednodušší if-else

2023-03-03 11:56 UTC, jan-potuznik-z commented on packetery/controllers/admin/PacketeryOrderGridController.php
> +                $customerShortenedName .= sprintf("%s. ", $namePart[0]);
Použij prosím substr.

2023-03-03 11:56 UTC, jan-potuznik-z commented on packetery/controllers/admin/PacketeryOrderGridController.php
> +    public function formatCustomerName($customerFullName)
Prestashop zkracuje jinak. Co tedy chceme? Nešlo by využít jeho metody?

2023-03-03 15:49 UTC, MMozola commented on packetery/controllers/admin/PacketeryOrderGridController.php
> -        $this->addRowAction('edit');
Hromadné akce fungují.

2023-03-12 13:37 UTC, packeta requested changes

2023-03-12 13:37 UTC, packeta commented on packetery/controllers/admin/PacketeryOrderGridController.php
> +        $customerLink = $this->getModule()->getAdminLink('AdminCustomers', ['id_customer' => $row['id_customer'], 'viewcustomer' => true]);
Za posledním prvkem pole se vždy píše ",".

2023-03-12 13:37 UTC, packeta commented on packetery/controllers/admin/PacketeryCarrierGridController.php
>          return '<a class="edit btn btn-default" href="' . $link . '"><i class="icon-pencil"></i> ' . $this->l('Edit', 'packeterycarriergridcontroller') . '</a>';
Proč toto nemáme v šabloně ?

2023-03-12 13:37 UTC, packeta commented on packetery/controllers/admin/PacketeryOrderGridController.php
> +        return $smarty->fetch(__DIR__ . '/../../views/templates/admin/weightEditable.tpl');
před return patří prázdný řádek.

2023-03-12 13:37 UTC, packeta commented on packetery/controllers/admin/PacketeryOrderGridController.php
> +        return $actionLinkHtml;
před return patří prázdný řádek

2023-03-12 13:37 UTC, packeta commented on packetery/packetery.php
> +            ) . '&' . http_build_query($params) . $anchor;
Proč zde nepoužíváš sprint pro sestavení stringu ?

2023-03-12 13:37 UTC, packeta commented on packetery/views/templates/admin/trackingLink.tpl
> +<a href="https://tracking.packeta.com/?id={$trackingNumber}" target="_blank">{$trackingNumber}</a>
url tracking.packeta.com máme v konstantě TRACKING_URL.  Nechceme mít url pro trasování na několika místech v kódu.

2023-03-17 12:14 UTC, MMozola commented on packetery/packetery.php
> +            ) . '&' . http_build_query($params) . $anchor;
Zde se to úplně nehodí, je to mnohem přehlednější a hezčí takhle, než ve formátu %s&%s%s

2023-03-21 08:33 UTC, packeta requested changes

2023-03-26 16:01 UTC, merged